name: 📜 مقولة اليوم 📅 📮

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "daily" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: daily
          fetch-depth: 0
      - name: Run script
        run: |
          git checkout master
          git pull
          git checkout daily
          git merge master

          php index.php
          git add .
          git push origin daily
          git status

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}
          force: true
          tags: true
          cleanup: false
          force_tags: true
          allow_empty_commit: true
          commit_message: "Daily Updated 📮 📜"
          commit_user_name: "Hasan"
          commit_user_email: "aldoyh@gmail.com"

          

