name: Deprecated - Fetch Comprehensive Quotes

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use 'Update Daily Quote' or local scripts."
